-- 사용자 계정 생성
CREATE USER c##MEDICAL IDENTIFIED BY MEDICAL;

-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##MEDICAL;

-- 테이블스페이스 설정
ALTER USER C##MEDICAL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 기존 객체 삭제
DROP SEQUENCE SEQ_RENNO;
DROP TABLE RENTAL;
DROP SEQUENCE SEQ_CUSTNO;
DROP TABLE CUSTOMER;
DROP SEQUENCE SEQ_DEVNO;
DROP TABLE DEVICE;

-- 테이블 생성
CREATE TABLE DEVICE(
    DEV_NO NUMBER PRIMARY KEY, --제품번호
    CATEGORY VARCHAR2(30) NOT NULL, --카테고리
    DEV_NAME VARCHAR2(50) NOT NULL, --제품명
    PRICE NUMBER, --가격
    ARRIVAL_DATE DATE DEFAULT SYSDATE NOT NULL --입고날짜
);

CREATE SEQUENCE SEQ_DEVNO
NOCACHE;

CREATE TABLE CUSTOMER(
    CUST_NO NUMBER PRIMARY KEY, --고객번호
    CUST_ID VARCHAR2(20) NOT NULL UNIQUE, --고객ID
    CUST_PW VARCHAR2(20) NOT NULL, --고객비번
    CUST_NAME VARCHAR2(20) NOT NULL, --고객이름
    CUST_PHONE VARCHAR2(20), --고객 전화번호
    CUST_ADDRESS VARCHAR2(100), --고객 주소
    CUST_JOINDATE DATE DEFAULT SYSDATE NOT NULL, -- 가입일
    ROLE VARCHAR2(10) DEFAULT 'CUSTOMER' NOT NULL CHECK(ROLE IN ('CUSTOMER', 'MANAGER')) -- 역할
);

CREATE SEQUENCE SEQ_CUSTNO
START WITH 1000
NOCACHE;

CREATE TABLE RENTAL(
    REN_NO NUMBER PRIMARY KEY, --대여번호
    DEV_NO NUMBER NOT NULL, --제품번호
    CUST_NO NUMBER NOT NULL, --고객번호
    REN_DATE DATE DEFAULT SYSDATE NOT NULL, --대여일
    STATUS VARCHAR2(20) DEFAULT '대여중' NOT NULL CHECK (STATUS IN ('대여중', '반납완료', '연체')), --대여상태
    CONSTRAINT FK_RENTAL_DEVICE FOREIGN KEY (DEV_NO) REFERENCES DEVICE(DEV_NO), --외래키
    CONSTRAINT FK_RENTAL_CUSTOMER FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER(CUST_NO) --외래키
);

CREATE SEQUENCE SEQ_RENNO
START WITH 5000
NOCACHE;

-- 제품 더미 데이터 삽입
INSERT INTO DEVICE
VALUES(SEQ_DEVNO.NEXTVAL, '침대', '의료용침대1', 1000000, SYSDATE);
INSERT INTO DEVICE
VALUES(SEQ_DEVNO.NEXTVAL, '휠체어', '이동식 휠체어1', 100000, SYSDATE);
INSERT INTO DEVICE
VALUES(SEQ_DEVNO.NEXTVAL, '지팡이', '보조지팡이1', 80000, SYSDATE);
INSERT INTO DEVICE
VALUES(SEQ_DEVNO.NEXTVAL, '침대', '의료용 침대2', 1500000, SYSDATE);
INSERT INTO DEVICE
VALUES(SEQ_DEVNO.NEXTVAL, '휠체어', '전동휠체어1', 1000000, SYSDATE);

-- 고객 더미 데이터 삽입
INSERT INTO CUSTOMER
VALUES(SEQ_CUSTNO.NEXTVAL, 'USER01', 'PASS01', '김길동', '010-1111-2222', '서울시 강남구', SYSDATE, 'CUSTOMER');
INSERT INTO CUSTOMER
VALUES(SEQ_CUSTNO.NEXTVAL, 'USER02', 'PASS02', '홍길동', '010-2222-3333', '경기도 성남시', SYSDATE, 'CUSTOMER');
INSERT INTO CUSTOMER
VALUES(SEQ_CUSTNO.NEXTVAL, 'USER03', 'PASS03', '박길동', '010-3333-4444', '서울시 서초구', SYSDATE, 'CUSTOMER');

-- 관리자 더미 데이터 삽입
INSERT INTO CUSTOMER
VALUES(SEQ_CUSTNO.NEXTVAL, 'MANAGER01', 'PASS01', '가길동', '010-9999-8888', '서울시 강남구', SYSDATE, 'MANAGER');
COMMIT;
